import combos.common as combo

LEFT_PLAYER_X = 0
LEFT_PLAYER_Y = 0
RIGHT_PLAYER_X = 0
RIGHT_PLAYER_Y = 0
CURRENT_FACING_SIDE = combo.MOVE_RIGHT
ENEMY_SPEAR = None
ENEMY_TELEPORTING = None
LAST_FRAME = None
NUMBER_OF_FRAMES_SINCE_LAST_FACING_SIDE_CHECK = 60
